osx_image: xcode8.3
language: objective-c
before_install:
- carthage bootstrap --platform Mac
xcode_project: MacPass.xcodeproj
xcode_scheme: MacPass
script: xcodebuild clean && xcodebuild build -project MacPass.xcodeproj -scheme MacPass CODE_SIGNING_REQUIRED=NO