osx_image: xcode8.3
xcode_project: MacPass.xcodeproj
xcode_scheme: MacPass
language: objective-c

before_install:
  - carthage bootstrap --platform Mac

before_depoly:
  - zip -9r MacPass-continuous.zip ./build/Build/Products/Release/MacPass.app

script: xcodebuild clean && xcodebuild build -configuration release -project MacPass.xcodeproj -scheme MacPass CODE_SIGNING_REQUIRED=NO -derivedDataPath ./build

#after_success:
#  - zip -9r ./build/Build/Products/Release/MacPass.app MacPass-continuous.zip
#  - wget -c https://github.com/MacPass/uploadtool/raw/master/upload.sh
#  - bash ./upload.sh build/*
  
branches:
  only:
    - /^(?i:continuous)$/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AEb7fgi29S3aXFt5bXz+lq1KHISumny6bf4j06JBC5gUrSs+dW0/tmVFq68XRAqigeOQU31wwv20f7OHiy+GRYDXM2xBsX9ZBQ2IilnaXlDy/mPsNcJJJsZ2gyodi3KnU0rZtTb93me2YyU86H4Na/gtaZZUKjLwCFtGGziExD8=
  file: MacPass-continuous.zip
  on:
    tags: true
    repo: mstarke/MacPass
    branch: continuous